{% raw %}
---

- name: Install python-pycurl
  apt: pkg=python-pycurl

- name: Add python apt repository
  apt_repository: repo={{python_ppa}} update_cache=yes

- name: Install python
  apt: pkg=python{{item}} state=present
  with_items: python_versions

- name: Install python-dev
  apt: pkg=python{{item}}-dev state=present
  with_items: python_versions
{% endraw %}
